import Lean

open Lean Elab Command

/-- Audit the complete imported `LeanRx.*` environment. Every unsafe declaration
in the exact allowlist below requires an explicit trust-boundary review. -/
elab "#leanrx_environment_audit" : command => do
  let env ← getEnv
  let reviewedUnsafe : Array Name := #[
    `LeanRx.Field.index._unsafe_rec,
    `LeanRx.Field.name._unsafe_rec,
    `LeanRx.Field.toFin._unsafe_rec,
    `LeanRx.Schema.names._unsafe_rec,
    `LeanRx.Schema.size._unsafe_rec,
    `LeanRx.Store.get._unsafe_rec,
    `LeanRx.Store.set._unsafe_rec,
    -- Generated dependent recursors for sealed representation metadata. These
    -- do not execute verified graph/propagation semantics.
    `LeanRx.RuntimeType.id._unsafe_rec,
    `LeanRx.RuntimeType.jsType._unsafe_rec,
    `LeanRx.RuntimeTypeId.debug._unsafe_rec,
    `LeanRx.JsType.debug._unsafe_rec,
    `LeanRx.Js.instBEqArgs.beq_1._unsafe_rec,
    `LeanRx.Js.instBEqArgs.beq_2._unsafe_rec,
    `LeanRx.Js.instBEqExpr.beq_1._unsafe_rec,
    `LeanRx.Js.instBEqExpr.beq_2._unsafe_rec,
    `LeanRx.Js.instBEqBlock.beq_1._unsafe_rec,
    `LeanRx.Js.instBEqBlock.beq_2._unsafe_rec,
    `LeanRx.Js.instBEqStmt.beq_1._unsafe_rec,
    `LeanRx.Js.instBEqStmt.beq_2._unsafe_rec,
    `LeanRx.Js.instReprArgs.repr_1._unsafe_rec,
    `LeanRx.Js.instReprArgs.repr_2._unsafe_rec,
    `LeanRx.Js.instReprExpr.repr_1._unsafe_rec,
    `LeanRx.Js.instReprExpr.repr_2._unsafe_rec,
    `LeanRx.Js.instReprBlock.repr_1._unsafe_rec,
    `LeanRx.Js.instReprBlock.repr_2._unsafe_rec,
    `LeanRx.Js.instReprStmt.repr_1._unsafe_rec,
    `LeanRx.Js.instReprStmt.repr_2._unsafe_rec,
    `LeanRx.Js.Args.ofList._unsafe_rec,
    `LeanRx.Js.Block.ofList._unsafe_rec,
    `LeanRx.Js.Printer.expr._unsafe_rec,
    `LeanRx.Js.Printer.exprArgs._unsafe_rec,
    `LeanRx.Lower.rxExpr._unsafe_rec,
    `LeanRx.ReactiveIR.Expr.debug._unsafe_rec,
    `LeanRx.ReactiveIR.Expr.runtimeTypeId._unsafe_rec,
    `LeanRx.Update.directWriteTargets._unsafe_rec,
    `LeanRx.Update.directReadDependencies._unsafe_rec,
    `LeanRx.Update.dispatchTargets._unsafe_rec,
    `LeanRx.ViewChildren.ofList._unsafe_rec,
    `LeanRx.ViewAttr.events._unsafe_rec,
    `LeanRx.ViewAttr.staticAttrs._unsafe_rec,
    `LeanRxDsl._aux_LeanRx_Elab_Component___elabRules_LeanRxDsl_leanrxComponent_1.unsafe_1,
    `LeanRx.Abstract.Reference.runDerived._unsafe_rec,
    `LeanRx.Abstract.SourceTransaction.apply._unsafe_rec,
    `LeanRx.Abstract.NestedTransaction.apply._unsafe_rec,
    `LeanRx.Abstract.Program.orderChecked._unsafe_rec,
    `LeanRx.AllInt.storeFrom._unsafe_rec,
    `LeanRx.Backend.Scalar.expr._unsafe_rec,
    `LeanRx.Backend.Scalar.helpers._unsafe_rec,
    `LeanRx.IntProgramSpec.derivedSteps._unsafe_rec,
    `LeanRx.IntProgramSpec.sinkSteps._unsafe_rec,
    `LeanRx.Abstract.Optimized.observe._unsafe_rec,
    `LeanRx.Abstract.Optimized.runDerived._unsafe_rec,
    `LeanRx.RxExpr.debug._unsafe_rec,
    `LeanRx.RxExpr.eval._unsafe_rec,
    `LeanRx.Schedule.position.loop._unsafe_rec,
    `LeanRx.instBEqJsType.beq._unsafe_rec,
    `LeanRx.instDecidableEqJsType.decEq._unsafe_rec,
    `LeanRx.instReprJsType.repr._unsafe_rec,
    `LeanRx.instBEqRuntimeTypeId.beq._unsafe_rec,
    `LeanRx.instDecidableEqRuntimeTypeId.decEq._unsafe_rec,
    `LeanRx.instReprRuntimeTypeId.repr._unsafe_rec,
    `LeanRx.instOrdRuntimeTypeId.ord._unsafe_rec
  ]
  -- Generated injectivity plus named membership/agreement lemmas use Lean's
  -- standard proposition-extensionality axiom. Each exact pair is reviewed;
  -- every other theorem/axiom pair fails closed.
  let reviewedAxiomUses : Array (Name × Array Name) := #[
    (`LeanRx.Abstract.DerivedStep.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.Eval.map._proof_1, #[``propext]),
    (`LeanRx.Abstract.Eval.map₂._proof_1, #[``propext]),
    (`LeanRx.Abstract.Eval.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.Optimized.DerivedResult.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.Optimized.ObservationResult.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.Optimized.StepResult.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.Optimized.not_pending_agree, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.Optimized.observe_eq, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.Optimized.runDerived_sound, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.Optimized.setChanged_tracks, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.Optimized.step_store_eq, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.Optimized.step_tracks, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.Program.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.Program.declares_of_checked, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.Program.order_of_checked, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.Program.wellFormed_of_check, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.RunResult.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.SinkStep.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.SourceWrite.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.State.mk.injEq, #[``propext]),
    (`LeanRx.Abstract.Store.set_other, #[``propext]),
    (`LeanRx.Abstract.Store.set_same, #[``propext]),
    (`LeanRx.Abstract.optimized_equivalent_to_reference, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.optimized_equivalent_for_flattened_nested_writes,
      #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.NestedTransaction.changedIds_tracks, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.NestedTransaction.flatten_valid, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.optimized_nextState_valid, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.optimized_store_eq_reference, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.Reference.initialize_valid, #[``propext]),
    (`LeanRx.Abstract.Reference.runDerived_cache_valid, #[``propext]),
    (`LeanRx.Abstract.Reference.runDerived_preserves_below, #[``propext]),
    (`LeanRx.Abstract.SourceTransaction.apply_eq_of_sourceCount_le, #[``propext]),
    (`LeanRx.Abstract.SourceTransaction.changedIds_tracks, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.SourceTransaction.changedIds_tracks._simp_1_2, #[``propext]),
    (`LeanRx.Abstract.SourceTransaction.changedIds_tracks._simp_1_3, #[``propext, ``Quot.sound]),
    (`LeanRx.Abstract.TraceEvent.derivedChanged.injEq, #[``propext]),
    (`LeanRx.Abstract.TraceEvent.derivedEvaluated.injEq, #[``propext]),
    (`LeanRx.Abstract.TraceEvent.derivedPending.injEq, #[``propext]),
    (`LeanRx.Abstract.TraceEvent.sinkEvaluated.injEq, #[``propext]),
    (`LeanRx.Abstract.TraceEvent.sinkPending.injEq, #[``propext]),
    (`LeanRx.Abstract.TraceEvent.sourceChanged.injEq, #[``propext]),
    (`LeanRx.Abstract.ValidState.mk.injEq, #[``propext]),
    (`LeanRx.Backend.ArtifactManifest.mk.injEq, #[``propext]),
    (`LeanRx.Backend.Component.Emitted.mk.injEq, #[``propext]),
    (`LeanRx.Backend.ManifestInput.mk.injEq, #[``propext]),
    (`LeanRx.Backend.Scalar.HelperBinding.mk.injEq, #[``propext]),
    (`LeanRx.Backend.Scalar.InputSpec.mk.injEq, #[``propext]),
    (`LeanRx.DepSet.contains_singleton, #[``propext]),
    (`LeanRx.DepSet.contains_singleton._simp_1_2, #[``propext]),
    (`LeanRx.DepSet.contains_union_left, #[``propext]),
    (`LeanRx.DepSet.contains_union_right, #[``propext]),
    (`LeanRx.DepSet.hasId_empty, #[``propext]),
    (`LeanRx.DepSet.hasId_singleton, #[``propext]),
    (`LeanRx.DepSet.hasId_union, #[``propext]),
    (`LeanRx.DepSet.hasId_union._simp_1_3, #[``propext]),
    (`LeanRx.SourcePos.mk.injEq, #[``propext]),
    (`LeanRx.SourceSpan.mk.injEq, #[``propext]),
    (`LeanRx.Field.there.injEq, #[``propext]),
    (`LeanRx.AllInt.field.injEq, #[``propext]),
    (`LeanRx.Graph.mk.injEq, #[``propext]),
    (`LeanRx.GraphError.mk.injEq, #[``propext]),
    (`LeanRx.JsType.array.injEq, #[``propext]),
    (`LeanRx.JsType.object.injEq, #[``propext]),
    (`LeanRx.RuntimeType.vector.injEq, #[``propext]),
    (`LeanRx.RuntimeTypeId.vector.injEq, #[``propext]),
    (`LeanRx.RuntimeTypeId.fin.injEq, #[``propext]),
    (`LeanRx.Js.Decl.function.injEq, #[``propext]),
    (`LeanRx.Js.AssignTarget.ident.injEq, #[``propext]),
    (`LeanRx.Js.AssignTarget.index.injEq, #[``propext]),
    (`LeanRx.Js.Args.cons.injEq, #[``propext]),
    (`LeanRx.Js.Block.cons.injEq, #[``propext]),
    (`LeanRx.Js.Error.mk.injEq, #[``propext]),
    (`LeanRx.Js.Export.mk.injEq, #[``propext]),
    (`LeanRx.Js.Expr.binary.injEq, #[``propext]),
    (`LeanRx.Js.Expr.call.injEq, #[``propext]),
    (`LeanRx.Js.Expr.conditional.injEq, #[``propext]),
    (`LeanRx.Js.Expr.ident.injEq, #[``propext]),
    (`LeanRx.Js.Expr.array.injEq, #[``propext]),
    (`LeanRx.Js.Expr.index.injEq, #[``propext]),
    (`LeanRx.Js.Expr.literal.injEq, #[``propext]),
    (`LeanRx.Js.Expr.unary.injEq, #[``propext]),
    (`LeanRx.Js.Function.mk.injEq, #[``propext]),
    (`LeanRx.Js.Import.mk.injEq, #[``propext]),
    (`LeanRx.Js.Literal.bigint.injEq, #[``propext]),
    (`LeanRx.Js.Literal.boolean.injEq, #[``propext]),
    (`LeanRx.Js.Literal.number.injEq, #[``propext]),
    (`LeanRx.Js.Literal.string.injEq, #[``propext]),
    (`LeanRx.Js.Module.mk.injEq, #[``propext]),
    (`LeanRx.Js.NameAllocator.mk.injEq, #[``propext]),
    (`LeanRx.Js.Stmt.const.injEq, #[``propext]),
    (`LeanRx.Js.Stmt.assign.injEq, #[``propext]),
    (`LeanRx.Js.Stmt.expr.injEq, #[``propext]),
    (`LeanRx.Js.Stmt.return.injEq, #[``propext]),
    (`LeanRx.Js.Stmt.ifThen.injEq, #[``propext]),
    (`LeanRx.Lower.rxExpr.eq_def, #[``propext, ``Quot.sound]),
    (`LeanRx.Lower.rxExpr._unary.eq_def, #[``propext, ``Quot.sound]),
    (`LeanRx.Lower.rxExpr._unary._proof_1, #[``propext, ``Quot.sound]),
    (`LeanRx.Lower.rxExpr._unary._proof_2, #[``propext, ``Quot.sound]),
    (`LeanRx.Lower.rxExpr._unary._proof_3, #[``propext, ``Quot.sound]),
    (`LeanRx.Lower.rxExpr._unary._proof_4, #[``propext, ``Quot.sound]),
    (`LeanRx.Lower.rxExpr._unary._proof_5, #[``propext, ``Quot.sound]),
    (`LeanRx.Lower.rxExpr._unary._proof_6, #[``propext, ``Quot.sound]),
    (`LeanRx.ReactiveIR.Expr.binary.injEq, #[``propext]),
    (`LeanRx.ReactiveIR.Expr.conditional.injEq, #[``propext]),
    (`LeanRx.ReactiveIR.Expr.input.injEq, #[``propext]),
    (`LeanRx.ReactiveIR.Expr.literal.injEq, #[``propext]),
    (`LeanRx.ReactiveIR.Expr.unary.injEq, #[``propext]),
    (`LeanRx.ReactiveIR.Literal.bool.injEq, #[``propext]),
    (`LeanRx.ReactiveIR.Literal.int.injEq, #[``propext]),
    (`LeanRx.ReactiveIR.Literal.nat.injEq, #[``propext]),
    (`LeanRx.ReactiveIR.Literal.string.injEq, #[``propext]),
    (`LeanRx.ReactiveIR.LowerError.mk.injEq, #[``propext]),
    (`LeanRx.IntProgramSpec.mk.injEq, #[``propext]),
    (`LeanRx.IntSinkSpec.observe.injEq, #[``propext]),
    (`LeanRx.IntValueSpec.derived.injEq, #[``propext]),
    (`LeanRx.IntValueSpec.source.injEq, #[``propext]),
    (`LeanRx.Node.mk.injEq, #[``propext]),
    (`LeanRx.NodeId.mk.injEq, #[``propext]),
    (`LeanRx.NodeSpec.mk.injEq, #[``propext]),
    (`LeanRx.RxExpr.binary.injEq, #[``propext]),
    (`LeanRx.RxExpr.debug.eq_def, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.debug._unary.eq_def, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.debug._unary._proof_1, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.debug._unary._proof_2, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.debug._unary._proof_3, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.debug._unary._proof_4, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.debug._unary._proof_5, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.debug._unary._proof_6, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval.eq_def, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval.eq_1, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval.eq_2, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval.eq_3, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval.eq_4, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval.eq_5, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval._unary.eq_def, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval._unary._proof_1, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval._unary._proof_2, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval._unary._proof_3, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval._unary._proof_4, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval._unary._proof_5, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval._unary._proof_6, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.eval_congr_on_deps, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.ifThenElse.injEq, #[``propext]),
    (`LeanRx.RxExpr.literal.injEq, #[``propext]),
    (`LeanRx.RxExpr.readWith.injEq, #[``propext]),
    (`LeanRx.RxExpr.toAbstractEval._proof_1, #[``propext, ``Quot.sound]),
    (`LeanRx.RxExpr.unary.injEq, #[``propext]),
    (`LeanRx.Schedule.mk.injEq, #[``propext]),
    (`LeanRx.ScalarLiteral.bool.injEq, #[``propext]),
    (`LeanRx.ScalarLiteral.int.injEq, #[``propext]),
    (`LeanRx.ScalarLiteral.nat.injEq, #[``propext]),
    (`LeanRx.ScalarLiteral.string.injEq, #[``propext]),
    (`LeanRx.Schema.field.injEq, #[``propext]),
    (`LeanRx.Store.agreeOn_empty, #[``propext]),
    (`LeanRx.Store.agreeOn_union_left, #[``propext]),
    (`LeanRx.Store.agreeOn_union_right, #[``propext]),
    (`LeanRx.Store.cons.injEq, #[``propext]),
    (`LeanRx.Graph.certified_schedule_respects_edges, #[``propext, ``Quot.sound]),
    (`LeanRx.TypedNodeRef.mk.injEq, #[``propext]),
    (`LeanRx.ComponentError.mk.injEq, #[``propext]),
    (`LeanRx.ComponentSpec.mk.injEq, #[``propext]),
    (`LeanRx.Backend.ComponentManifest.mk.injEq, #[``propext]),
    (`LeanRx.SurfaceDecl.mk.injEq, #[``propext]),
    (`LeanRx.Cli.Command.build.injEq, #[``propext]),
    (`LeanRx.Cli.Command.check.injEq, #[``propext]),
    (`LeanRx.Cli.Command.graph.injEq, #[``propext]),
    (`LeanRx.Cli.Error.mk.injEq, #[``propext]),
    (`LeanRx.EventBinding.mk.injEq, #[``propext]),
    (`LeanRx.EventSpec.mk.injEq, #[``propext]),
    (`LeanRx.EventSummary.mk.injEq, #[``propext]),
    (`LeanRx.MountChildren.cons.injEq, #[``propext]),
    (`LeanRx.MountedEvent.mk.injEq, #[``propext]),
    (`LeanRx.MountNode.element.injEq, #[``propext]),
    (`LeanRx.MountNode.text.injEq, #[``propext]),
    (`LeanRx.StaticAttr.ariaLabel.injEq, #[``propext]),
    (`LeanRx.StaticAttr.buttonType.injEq, #[``propext]),
    (`LeanRx.StaticAttr.className.injEq, #[``propext]),
    (`LeanRx.StaticAttr.id.injEq, #[``propext]),
    (`LeanRx.TextSink.mk.injEq, #[``propext]),
    (`LeanRx.Update.sequence.injEq, #[``propext]),
    (`LeanRx.Update.dispatch.injEq, #[``propext]),
    (`LeanRx.Update.set.injEq, #[``propext]),
    (`LeanRx.ValueSpec.derived.injEq, #[``propext]),
    (`LeanRx.ValueSpec.source.injEq, #[``propext]),
    (`LeanRx.View.element.injEq, #[``propext]),
    (`LeanRx.ViewAttr.event.injEq, #[``propext]),
    (`LeanRx.ViewAttr.static.injEq, #[``propext]),
    (`LeanRx.View.scalarText.injEq, #[``propext]),
    (`LeanRx.View.text.injEq, #[``propext]),
    (`LeanRx.ViewChildren.cons.injEq, #[``propext]),
    (`LeanRx.ViewSplit.mk.injEq, #[``propext])
  ]
  let declarations := (env.constants.toList.filter fun (name, _) =>
      name.toString.startsWith "LeanRx." ||
        name.toString.startsWith "LeanRxDsl.").toArray.qsort fun a b =>
    Name.lt a.1 b.1
  let requiredImports : Array Name := #[
    `LeanRx.version, `LeanRx.SourcePos, `LeanRx.Cli.Driver.run
  ]
  for name in requiredImports do
    unless declarations.any (fun entry => entry.1 == name) do
      throwError "environment audit is missing required imported declaration '{name}'"
  let mut theoremCount : Nat := 0
  let mut reviewedAxiomCount : Nat := 0
  let mut reviewedUnsafeCount : Nat := 0
  for (name, info) in declarations do
    if info.isAxiom then
      throwError "public LeanRx axiom '{name}' is not allowed"
    if info.isUnsafe || info.isPartial then
      unless reviewedUnsafe.contains name do
        throwError "unreviewed unsafe or partial LeanRx declaration: '{name}'"
      reviewedUnsafeCount := reviewedUnsafeCount + 1
    if info.isTheorem then
      theoremCount := theoremCount + 1
      let axioms ← Lean.collectAxioms name
      let expected := reviewedAxiomUses.find? (fun entry => entry.1 == name)
        |>.map (·.2) |>.getD #[]
      unless axioms == expected do
        throwError "public theorem '{name}' axiom manifest mismatch; expected {expected.toList}, got {axioms.toList}"
      unless axioms.isEmpty do
        reviewedAxiomCount := reviewedAxiomCount + 1
  for (name, _) in reviewedAxiomUses do
    unless declarations.any (fun entry => entry.1 == name) do
      throwError "reviewed axiom manifest names missing declaration '{name}'"
  for name in reviewedUnsafe do
    unless declarations.any (fun entry => entry.1 == name) do
      throwError "reviewed unsafe manifest names missing declaration '{name}'"
  logInfo m!"LeanRx environment audit passed: {theoremCount} public theorem(s), {reviewedAxiomCount} exact reviewed axiom use(s), {reviewedUnsafeCount} exact generated unsafe helper(s)"
