#!/usr/bin/env bash
set -euo pipefail

first="$(mktemp -d)"
second="$(mktemp -d)"
trap 'rm -rf -- "$first" "$second"' EXIT

lake exe leanrx_counter_js -- "$first/dist"
lake exe leanrx_counter_js -- "$second/dist"
lake exe leanrx_diamond_js -- "$first/diamond"
lake exe leanrx_diamond_js -- "$second/diamond"
lake exe leanrx_echo_js -- "$first/echo"
lake exe leanrx_echo_js -- "$second/echo"
lake exe leanrx_filter_js -- "$first/filter"
lake exe leanrx_filter_js -- "$second/filter"
lake exe leanrx_nest_js -- "$first/nest"
lake exe leanrx_nest_js -- "$second/nest"
lake exe leanrx_tabs_js -- "$first/tabs"
lake exe leanrx_tabs_js -- "$second/tabs"
lake exe leanrx_temperature_js -- "$first/temperature"
lake exe leanrx_temperature_js -- "$second/temperature"
lake exe leanrx_validated_form_js -- "$first/validated-form"
lake exe leanrx_validated_form_js -- "$second/validated-form"
lake exe leanrx_todo_js -- "$first/todo"
lake exe leanrx_todo_js -- "$second/todo"
lake exe leanrx_notes_js -- "$first/notes"
lake exe leanrx_notes_js -- "$second/notes"
lake exe leanrx_issue_browser_js -- "$first/issues"
lake exe leanrx_issue_browser_js -- "$second/issues"
lake exe leanrx_data_grid_js -- "$first/grid"
lake exe leanrx_data_grid_js -- "$second/grid"
lake exe leanrx_docs_js -- "$first/docs"
lake exe leanrx_docs_js -- "$second/docs"

diff -ru "$first/dist/" "$second/dist/"
diff -ru "$first/diamond/" "$second/diamond/"
diff -ru "$first/echo/" "$second/echo/"
diff -ru "$first/filter/" "$second/filter/"
diff -ru "$first/nest/" "$second/nest/"
diff -ru "$first/tabs/" "$second/tabs/"
diff -ru "$first/temperature/" "$second/temperature/"
diff -ru "$first/validated-form/" "$second/validated-form/"
diff -ru "$first/todo/" "$second/todo/"
diff -ru "$first/notes/" "$second/notes/"
diff -ru "$first/issues/" "$second/issues/"
diff -ru "$first/grid/" "$second/grid/"
diff -ru "$first/docs/" "$second/docs/"
node --check "$first/dist/Counter.mjs"
node --check "$first/dist/leanrx_dom.mjs"
node Test/js/component_artifacts.mjs "$first/dist"
node --check "$first/diamond/DiamondLab.mjs"
node Test/js/diamond_artifacts.mjs "$first/diamond"
node --check "$first/echo/EchoLab.mjs"
node --check "$first/echo/leanrx_form_events.mjs"
node Test/js/echo_artifacts.mjs "$first/echo"
node --check "$first/filter/FilterLab.mjs"
node Test/js/filter_artifacts.mjs "$first/filter"
node --check "$first/nest/NestLab.mjs"
node --check "$first/nest/Pulse.mjs"
node Test/js/nest_artifacts.mjs "$first/nest"
node --check "$first/tabs/DependentTabs.mjs"
node Test/js/tabs_artifacts.mjs "$first/tabs"
node --check "$first/temperature/TemperatureConverter.mjs"
node --check "$first/temperature/leanrx_form_events.mjs"
node Test/js/temperature_artifacts.mjs "$first/temperature"
node --check "$first/validated-form/ValidatedForm.mjs"
node Test/js/validated_form_artifacts.mjs "$first/validated-form"
node --check "$first/todo/TodoMVC.mjs"
node Test/js/todo_artifacts.mjs "$first/todo"
node --check "$first/notes/Notes.mjs"
node Test/js/notes_artifacts.mjs "$first/notes"
node --check "$first/issues/IssueBrowser.mjs"
node Test/js/issue_browser_artifacts.mjs "$first/issues"
node --check "$first/grid/DataGrid.mjs"
node --check "$first/grid/DataGrid.min.mjs"
node Test/js/grid_artifacts.mjs "$first/grid"
node --check "$first/docs/LeanRxDocs.mjs"
node Test/js/docs_artifacts.mjs "$first/docs"
lake env lean "$first/docs/LeanRxDocs.generated.lean"
